import{a as S,S as q,i as n}from"./assets/vendor-BNibzuFn.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const a of o.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function s(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();const v="52616200-fc5cfd906759777ac22999e8c",P="https://pixabay.com/api/";async function d(r,t){const i={key:v,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:t};return(await S.get(P,{params:i})).data}const u=document.querySelector(".gallery"),m=document.querySelector(".loader"),f=document.querySelector(".load-more");let B=new q(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250});function g(r){const t=r.map(({webformatURL:i,largeImageURL:s,tags:e,likes:o,views:a,comments:L,downloads:w})=>`
        <li class="gallery-item">
          <a class="gallery-link" href="${s}">
            <img class="gallery-image" src="${i}" alt="${e}" />
          </a>
          <ul class="info">
            <li><b>Likes:</b> ${o}</li>
            <li><b>Views:</b> ${a}</li>
            <li><b>Comments:</b> ${L}</li>
            <li><b>Downloads:</b> ${w}</li>
          </ul>
        </li>`).join("");u.insertAdjacentHTML("beforeend",t),B.refresh()}function E(){u.innerHTML=""}function h(){m.classList.remove("is-hidden")}function y(){m.classList.add("is-hidden")}function M(){f.classList.remove("is-hidden")}function p(){f.classList.add("is-hidden")}const $=document.querySelector(".form"),O=document.querySelector(".load-more");let c="",l=1,b=0;$.addEventListener("submit",async r=>{if(r.preventDefault(),c=r.target.elements["search-text"].value.trim(),!c){n.warning({title:"Oops!",message:"Please enter a search term!",position:"topRight"});return}l=1,E(),p(),h();try{const t=await d(c,l);if(b=t.totalHits,t.hits.length===0){n.info({title:"No results",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}g(t.hits),t.totalHits>15&&M()}catch{n.error({title:"Error",message:"Something went wrong. Please try again later.",position:"topRight"})}finally{y()}});O.addEventListener("click",async()=>{l+=1,h();try{const r=await d(c,l);g(r.hits);const t=Math.ceil(b/15);l>=t&&(p(),n.info({message:"We're sorry, but you've reached the end of search results.",position:"bottomRight"}));const{height:i}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:i*2,behavior:"smooth"})}catch{n.error({title:"Error",message:"Something went wrong while loading more images.",position:"topRight"})}finally{y()}});
//# sourceMappingURL=index.js.map
